# Generated by Django 2.2.3 on 2019-07-30 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=128)),
                ('text_body', models.TextField(null=True)),
                ('cre_time', models.DateTimeField(auto_now_add=True)),
                ('mod_time', models.DateTimeField(auto_now_add=True)),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.User')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['cre_time'],
            },
        ),
    ]
