# Generated by Django 2.2.3 on 2019-08-06 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='hashID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UhashID', models.CharField(max_length=128)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.User')),
            ],
            options={
                'verbose_name': 'Hash',
                'verbose_name_plural': 'Hash',
                'ordering': ['c_time'],
            },
        ),
    ]
